apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: store-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: store-app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics